//Generated by rmud area generator
public class _00_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Lighthouse";

        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_02_10");
    }
}
