//Generated by rmud area generator
public class _02_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Docks";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_02_12");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_04_14");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_04_16");
    }
}
