//Generated by rmud area generator
public class _02_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_04_06");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_02_10");
    }
}
