//Generated by rmud area generator
public class _02_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Docks";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_02_10");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_02_14");
    }
}
