//Generated by rmud area generator
public class _02_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_02_08");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_04_10");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_02_12");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_00_08");
    }
}
