//Generated by rmud area generator
public class _02_02 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_04_00");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_04_04");
    }
}
