//Generated by rmud area generator
public class _04_00 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_00");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_02_02");
    }
}
