//Generated by rmud area generator
public class _04_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_04_04");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_02_08");
    }
}
