//Generated by rmud area generator
public class _04_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_14");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_02_14");
    }
}
