//Generated by rmud area generator
public class _04_04 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_04");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_04_06");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_02_02");
    }
}
