//Generated by rmud area generator
public class _04_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_08");
    }
}
