//Generated by rmud area generator
public class _04_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_04_16");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_18");
    }
}
