//Generated by rmud area generator
public class _04_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bookstore";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_12");
    }
}
