//Generated by rmud area generator
public class _04_02 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bed and Breakfast";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_02");
    }
}
