//Generated by rmud area generator
public class _04_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - allyway";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_10");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_02_10");
    }
}
