//Generated by rmud area generator
public class _04_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Docks";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_06_16");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_04_18");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_02_14");
    }
}
