//Generated by rmud area generator
public class _06_02 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_08_00");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_08_02");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_06_04");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_04_02");
    }
}
