//Generated by rmud area generator
public class _06_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Restuarant";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_08_16");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_04_16");
    }
}
