//Generated by rmud area generator
public class _06_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_06_04");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_08_06");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_06_08");
    }
}
