//Generated by rmud area generator
public class _06_04 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_06_02");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_06_06");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_04_04");
    }
}
