//Generated by rmud area generator
public class _06_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_06_08");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_08_10");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_06_12");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_04_10");
    }
}
