//Generated by rmud area generator
public class _06_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_08_18");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_04_18");
    }
}
