//Generated by rmud area generator
public class _06_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_06_12");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_08_14");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_08_16");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_04_14");
    }
}
