//Generated by rmud area generator
public class _08_02 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Cathederal";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_10_02");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_06_02");
    }
}
