//Generated by rmud area generator
public class _08_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_10_16");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_10_18");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_06_16");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_06_14");
    }
}
