//Generated by rmud area generator
public class _08_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Post Office";

        OpenLink(RMUD.Direction.WEST, "port-ivy/_06_08");
    }
}
