//Generated by rmud area generator
public class _08_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Grocery";

        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_08_14");
    }
}
