//Generated by rmud area generator
public class _08_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_10_18");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_10_20");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_06_18");
    }
}
