//Generated by rmud area generator
public class _08_00 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Shipwreck";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_10_00");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_06_02");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_06_00");
    }
}
