//Generated by rmud area generator
public class _08_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bank";

        OpenLink(RMUD.Direction.WEST, "port-ivy/_06_10");
    }
}
