//Generated by rmud area generator
public class _08_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_08_04");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_10_06");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_06_06");
    }
}
