//Generated by rmud area generator
public class _10_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_12_18");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_08_18");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_08_16");
    }
}
