//Generated by rmud area generator
public class _10_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_12_08");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_10_12");
    }
}
