//Generated by rmud area generator
public class _10_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Antique Mall";

        OpenLink(RMUD.Direction.WEST, "port-ivy/_08_16");
    }
}
