//Generated by rmud area generator
public class _10_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_10_10");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_12_12");
    }
}
