//Generated by rmud area generator
public class _10_20 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_12_20");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_08_18");
    }
}
