//Generated by rmud area generator
public class _10_02 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Cementery";

        OpenLink(RMUD.Direction.WEST, "port-ivy/_08_02");
    }
}
