//Generated by rmud area generator
public class _10_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_10_04");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_12_06");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_10_08");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_08_06");
    }
}
