//Generated by rmud area generator
public class _10_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_10_06");
    }
}
