//Generated by rmud area generator
public class _10_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_12_12");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_12_14");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_12_16");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_08_14");
    }
}
