//Generated by rmud area generator
public class _12_20 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_14_20");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_10_20");
    }
}
