//Generated by rmud area generator
public class _12_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Hotel";

        OpenLink(RMUD.Direction.WEST, "port-ivy/_10_14");
    }
}
