//Generated by rmud area generator
public class _12_04 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_12_06");
    }
}
