//Generated by rmud area generator
public class _12_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_12_04");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_14_06");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_14_08");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_10_06");
    }
}
