//Generated by rmud area generator
public class _12_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_14_10");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_14_14");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_10_14");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_10_12");
    }
}
