//Generated by rmud area generator
public class _12_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_12_16");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_14_18");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_10_18");
    }
}
