//Generated by rmud area generator
public class _12_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Monument";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_14_14");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_12_18");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_10_14");
    }
}
