//Generated by rmud area generator
public class _12_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_14_08");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_10_10");
    }
}
