//Generated by rmud area generator
public class _12_00 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_14_00");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_10_00");
    }
}
