//Generated by rmud area generator
public class _14_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_16_16");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_12_18");
    }
}
