//Generated by rmud area generator
public class _14_20 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_16_18");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_12_20");
    }
}
