//Generated by rmud area generator
public class _14_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_14_10");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_12_08");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_12_06");
    }
}
