//Generated by rmud area generator
public class _14_00 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_16_02");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_12_00");
    }
}
