//Generated by rmud area generator
public class _14_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Chamber of Commerce";

        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_12_16");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_12_12");
    }
}
