//Generated by rmud area generator
public class _14_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_14_08");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_16_10");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_12_12");
    }
}
