//Generated by rmud area generator
public class _14_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_14_04");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_16_06");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_12_06");
    }
}
