//Generated by rmud area generator
public class _16_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_18_10");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_14_10");
    }
}
