//Generated by rmud area generator
public class _16_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_18_14");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_18_16");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_14_18");
    }
}
