//Generated by rmud area generator
public class _16_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_18_04");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_18_06");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_18_08");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_14_06");
    }
}
