//Generated by rmud area generator
public class _16_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_18_12");
    }
}
