//Generated by rmud area generator
public class _16_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_18_14");
    }
}
