//Generated by rmud area generator
public class _16_02 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_18_02");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_14_00");
    }
}
