//Generated by rmud area generator
public class _16_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_18_18");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_14_20");
    }
}
