//Generated by rmud area generator
public class _18_04 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_16_06");
    }
}
