//Generated by rmud area generator
public class _18_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_20_18");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_16_18");
    }
}
