//Generated by rmud area generator
public class _18_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_20_08");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_18_10");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_16_06");
    }
}
