//Generated by rmud area generator
public class _18_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_18_10");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_20_12");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_18_14");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_16_12");
    }
}
