//Generated by rmud area generator
public class _18_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_18_12");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_20_14");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_16_16");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_16_14");
    }
}
