//Generated by rmud area generator
public class _18_02 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_20_04");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_16_02");
    }
}
