//Generated by rmud area generator
public class _18_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - School";

        OpenLink(RMUD.Direction.WEST, "port-ivy/_16_16");
    }
}
