//Generated by rmud area generator
public class _20_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

        OpenLink(RMUD.Direction.WEST, "port-ivy/_18_14");
    }
}
