//Generated by rmud area generator
public class _20_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_22_12");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_18_10");
    }
}
