//Generated by rmud area generator
public class _20_18 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_22_16");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_18_18");
    }
}
