//Generated by rmud area generator
public class _20_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_22_06");
        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_22_10");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_18_08");
    }
}
