//Generated by rmud area generator
public class _20_04 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_22_04");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_18_02");
    }
}
