//Generated by rmud area generator
public class _22_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_22_04");
        OpenLink(RMUD.Direction.EAST, "port-ivy/_24_06");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_20_08");
    }
}
