//Generated by rmud area generator
public class _22_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_24_12");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_20_10");
    }
}
