//Generated by rmud area generator
public class _22_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Comber's Shack";

        OpenLink(RMUD.Direction.EAST, "port-ivy/_24_10");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_20_08");
    }
}
