//Generated by rmud area generator
public class _22_16 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_24_14");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_20_18");
    }
}
