//Generated by rmud area generator
public class _22_04 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_22_06");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_20_04");
    }
}
