//Generated by rmud area generator
public class _24_14 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_24_12");
        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_22_16");
    }
}
