//Generated by rmud area generator
public class _24_12 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.NORTH, "port-ivy/_24_10");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_24_14");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_22_12");
    }
}
