//Generated by rmud area generator
public class _24_10 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/_26_08");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/_24_12");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_22_10");
    }
}
