//Generated by rmud area generator
public class _24_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bluffs";

        OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/_26_08");
        OpenLink(RMUD.Direction.WEST, "port-ivy/_22_06");
    }
}
