//Generated by rmud area generator
public class _26_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach";

        OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/_24_10");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/_24_06");
    }
}
