//Generated by rmud area generator
public class Alleyway : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Alleyway";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_North_4");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Beach__West_Side_1");
    }
}
