//Generated by rmud area generator
public class Allyway : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Allyway";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_North_4");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Beach__West_Side_1");
    }
}
