//Generated by rmud area generator
public class Antique_Mall : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Antique Mall";

      OpenLink(RMUD.Direction.WEST, "port-ivy/Main_St_South_0");
    }
}
