//Generated by rmud area generator
public class Bank : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bank";

      OpenLink(RMUD.Direction.WEST, "port-ivy/Main_St_North_4");
    }
}
