//Generated by rmud area generator
public class Beach__East_Side_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, East Side";

      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Beach__East_Side_1");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Seaside_Ridge_3");
    }
}
