//Generated by rmud area generator
public class Beach__East_Side_3 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, East Side";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Beach__East_Side_2");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Beach__East_Side_4");
    }
}
