//Generated by rmud area generator
public class Beach__North_Side_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, North Side";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Beach__North_Side_1");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Beach__West_Side_0");
    }
}
