//Generated by rmud area generator
public class Beach__North_Side_6 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, North Side";

      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Seaside_Ridge_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Beach__North_Side_5");
    }
}
