//Generated by rmud area generator
public class Beach__East_Side_4 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, East Side";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Beach__East_Side_3");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Beach__South_Side");
    }
}
