//Generated by rmud area generator
public class Beach__East_Side_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, East Side";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Beach__East_Side_0");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Beach__East_Side_2");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Comber_s_Shack");
    }
}
