//Generated by rmud area generator
public class Beach__West_Side_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, West Side";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Beach__North_Side_0");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Thornton_Heights_0");
    }
}
