//Generated by rmud area generator
public class Beach__South_Side : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, South Side";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Beach__East_Side_4");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Tide_Crush_Bluffs_1");
    }
}
