//Generated by rmud area generator
public class Beach__East_Side_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, East Side";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Beach__East_Side_1");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Beach__East_Side_3");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Dock_St_4");
    }
}
