//Generated by rmud area generator
public class Beach__North_Side_5 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Beach, North Side";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Beach__North_Side_6");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Beach__North_Side_4");
    }
}
