//Generated by rmud area generator
public class Bed_and_Breakfast : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bed and Breakfast";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_North_0");
    }
}
