//Generated by rmud area generator
public class Bookstore : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Bookstore";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_North_5");
    }
}
