//Generated by rmud area generator
public class Cathederal : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Cathederal";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Cementery");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Main_St_North_0");
    }
}
