//Generated by rmud area generator
public class Cementery : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Cementery";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Forest_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Cathederal");
    }
}
