//Generated by rmud area generator
public class Cemetery : RMUD.Room {
    public override void Initialize() {
		RoomType = RMUD.RoomType.Exterior;
		Short = "The cemetery";
		Long = "Gravestones everywhere.";

		OpenLink(RMUD.Direction.EAST, "port-ivy/Forest_0");
		OpenLink(RMUD.Direction.WEST, "port-ivy/cathedral/main-nef");
    }
}
