//Generated by rmud area generator
public class Chamber_of_Commerce : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Chamber of Commerce";

      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Monument");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Dock_St_3");
    }
}
