//Generated by rmud area generator
public class Comber_s_Shack : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Comber's Shack";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Beach__East_Side_1");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Forest_3");
    }
}
