//Generated by rmud area generator
public class Crescent_St_Northwest_4 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St Northwest";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/House_04");
      OpenLink(RMUD.Direction.EAST, "port-ivy/House_05");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Crescent_St_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Crescent_St_Northwest_3");
    }
}
