//Generated by rmud area generator
public class Crescent_St_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Forest_3");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Crescent_and_Dock");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Crescent_St_Northwest_4");
    }
}
