//Generated by rmud area generator
public class Crescent_St_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Crescent_St_1");
      OpenLink(RMUD.Direction.EAST, "port-ivy/House_11");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Crescent_St_Southwest_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/House_10");
    }
}
