//Generated by rmud area generator
public class Crescent_St_Northwest_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St Northwest";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/House_01");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Crescent_St_Northwest_2");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/House_07");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Crescent_St_Northwest_0");
    }
}
