//Generated by rmud area generator
public class Crescent_and_Dock : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent and Dock";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Crescent_St_0");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Dock_St_2");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Crescent_St_1");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Dock_St_1");
    }
}
