//Generated by rmud area generator
public class Crescent_St_Northwest_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St Northwest";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/House_00");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Crescent_St_Northwest_1");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Main_St_North_2");
    }
}
