//Generated by rmud area generator
public class Crescent_St_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Crescent_and_Dock");
      OpenLink(RMUD.Direction.EAST, "port-ivy/House_09");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Crescent_St_2");
      OpenLink(RMUD.Direction.WEST, "port-ivy/House_08");
    }
}
