//Generated by rmud area generator
public class Crescent_St_Southwest_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Crescent St Southwest";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Crescent_St_Southwest_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Crescent_St_Southwest_1");
    }
}
