//Generated by rmud area generator
public class Dock_St_5 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_and_Dock");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Docks_1");
    }
}
