//Generated by rmud area generator
public class Dock_St_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Forest_2");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Dock_St_1");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Dock_St_3");
    }
}
