//Generated by rmud area generator
public class Docks_2 : RMUD.Room {
    public override void Initialize() {
        RoomType = RMUD.RoomType.Exterior;
        Short = "Port Ivy - Docks";
        Long = "";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Restaurant");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Waterfront_Park_0");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Docks_1");
    }
}
