//Generated by rmud area generator
public class Docks_0 : RMUD.Room {
    public override void Initialize() {
        RoomType = RMUD.RoomType.Exterior;
        Short = "Port Ivy - Old Docks";
        Long = "The ground here is worn-down stone. The boats are sailboats, and judging by the barnacles on the hulls, they have not been used in a while. The Esperanza, the largest boat here, is docked in the middle, in plain sight. The waves break along the stone docks with a rhythmic sound. The back of the bookstore shows through the trees to the east. North of here, the docks give way to a trail to the beach, and the docks themselves continue to the south.";
      OpenLink(RMUD.Direction.NORTH, "port-ivy/Beach__West_Side_1");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Docks_1");
    }
}
