//Generated by rmud area generator
public class Docks_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Docks";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Beach__West_Side_1");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Docks_1");
    }
}
