//Generated by rmud area generator
public class Dock_St_6 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Grocery");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Dock_St_7");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Main_and_Dock");
    }
}
