//Generated by rmud area generator
public class Dock_St_7 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Dock_St_3");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Hotel");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Monument");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Dock_St_6");
    }
}
