//Generated by rmud area generator
public class Docks_1 : RMUD.Room {
    public override void Initialize() {
        RoomType = RMUD.RoomType.Exterior;
        Short = "Port Ivy - Docks";
        Long = "The docks are separated from Docks Street by two street lamps between which hang those small triangle flags that one sees during town faires. The ground is smooth stone. The boats look clean and maintained. The waves break gently along the stone of the docks. North of here, the docks continue and look more rundown. East, Docks Street begins, and Southeast of here, the docks border the Waterfront Park and the Restaurant.";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Docks_0");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Dock_St_5");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Docks_2");
    }
}
