//Generated by rmud area generator
public class Docks_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Docks";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Docks_0");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Dock_St_5");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Docks_2");
    }
}
