//Generated by rmud area generator
public class Dock_St_4 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Dock St";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Beach__East_Side_2");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Dock_St_2");
    }
}
