//Generated by rmud area generator
public class Forest_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Forest_2");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Forest_4");
    }
}
