//Generated by rmud area generator
public class Forest_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Dock_St_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Forest_1");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Crescent_St_Northwest_2");
    }
}
