//Generated by rmud area generator
public class Forest_5 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Forest_4");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Dock_St_3");
    }
}
