//Generated by rmud area generator
public class Forest_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

      OpenLink(RMUD.Direction.WEST, "port-ivy/Cementery");
    }
}
