//Generated by rmud area generator
public class Forest_3 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Forest";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Seaside_Ridge_2");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Comber_s_Shack");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Crescent_St_0");
    }
}
