//Generated by rmud area generator
public class Grocery : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Grocery";

      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Dock_St_6");
    }
}
