//Generated by rmud area generator
public class Hotel : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Hotel";

      OpenLink(RMUD.Direction.WEST, "port-ivy/Dock_St_7");
    }
}
