//Generated by rmud area generator
public class House_08 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Crescent_St_1");
    }
}
