//Generated by rmud area generator
public class House_03 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Crescent_St_Northwest_3");
    }
}
