//Generated by rmud area generator
public class House_04 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Crescent_St_Northwest_4");
    }
}
