//Generated by rmud area generator
public class House_06 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - House";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_North_3");
    }
}
