//Generated by rmud area generator
public class Lighthouse : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Lighthouse";

      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Beach__West_Side_1");
    }
}
