//Generated by rmud area generator
public class Main_and_Dock : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main and Dock";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Main_St_North_5");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Dock_St_6");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Main_St_South_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Dock_St_5");
    }
}
