//Generated by rmud area generator
public class Main_St_North_4 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St North";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Main_St_North_3");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Bank");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Main_St_North_5");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Alleyway");
    }
}
