//Generated by rmud area generator
public class Main_St_North_3 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St North";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Main_St_North_2");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Post_Office");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Main_St_North_4");
      OpenLink(RMUD.Direction.WEST, "port-ivy/House_06");
    }
}
