//Generated by rmud area generator
public class Main_St_South_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Main St South";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Crescent_St_Southwest_1");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Waterfront_Park_2");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Main_St_South_0");
    }
}
