//Generated by rmud area generator
public class Monument : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Monument";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Chamber_of_Commerce");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Crescent_St_Southwest_1");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Dock_St_7");
    }
}
