//import scenery_lamp

//Generated by rmud area generator
public class Monument : RMUD.Room {
    public override void Initialize()
    {
        Short = "Port Ivy - Monument to the Nickering Nag";
        Long = new RMUD.DescriptiveText((actor, owner) =>
        {
            var builder = new System.Text.StringBuilder();
            builder.Append("A twisting path winds its way in what is more or less a circle around a statue of a rearing horse. The horse is a gaunt and twisted nag.");
            if (RMUD.Mud.IsNight) builder.Append(" Spotlights shine up at the beast, painting her underside in bright tones.");
            return builder.ToString();
        });

        AddScenery(new scenery_lamp("spotlight spotlights light lights spot", "These bright lights are pointed at the horse. They make it kind of unearthly."));

        AddScenery("It's a very unattractive horse, full of taunt muscles and popping veins, but not in the nice way. In a very terribly ugly way.", "horse", "nickering", "nag", "monument", "beast", "rearing", "statue");

        OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Chamber_of_Commerce");
        OpenLink(RMUD.Direction.SOUTH, "port-ivy/Crescent_St_Southwest_1");
        OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Dock_St_7");
    }
}
