//Generated by rmud area generator
public class Post_Office : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Post Office";

      OpenLink(RMUD.Direction.WEST, "port-ivy/Main_St_North_3");
    }
}
