//Generated by rmud area generator
public class Restuarant : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Restuarant";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_South_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Docks_2");
    }
}
