//Generated by rmud area generator
public class School : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - School";

      OpenLink(RMUD.Direction.WEST, "port-ivy/Crescent_St_Southwest_0");
    }
}
