//Generated by rmud area generator
public class Seaside_Ridge_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Seaside Ridge";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Seaside_Ridge_1");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Seaside_Ridge_3");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Forest_3");
    }
}
