//Generated by rmud area generator
public class Seaside_Ridge_3 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Seaside Ridge";

      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Beach__East_Side_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Seaside_Ridge_2");
    }
}
