//Generated by rmud area generator
public class Seaside_Ridge_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Seaside Ridge";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Seaside_Ridge_1");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Beach__North_Side_6");
    }
}
