//Generated by rmud area generator
public class Seaside_Ridge_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Seaside Ridge";

      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Seaside_Ridge_2");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Seaside_Ridge_0");
    }
}
