//Generated by rmud area generator
public class Thornton_Heights_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Thornton Heights";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Thornton_Heights_0");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Thornton_Heights_2");
    }
}
