//Generated by rmud area generator
public class Thornton_Heights_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Thornton Heights";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_North_1");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Thornton_Heights_1");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Beach__West_Side_0");
    }
}
