//Generated by rmud area generator
public class Thornton_Heights_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Thornton Heights";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Thornton_Heights_1");
      OpenLink(RMUD.Direction.SOUTH, "port-ivy/Beach__West_Side_1");
    }
}
