//Generated by rmud area generator
public class Tide_Crush_Bluffs_1 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Tide Crush Bluffs";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Beach__South_Side");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Tide_Crush_Bluffs_0");
    }
}
