//Generated by rmud area generator
public class Tide_Crush_Bluffs_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Tide Crush Bluffs";

      OpenLink(RMUD.Direction.NORTHEAST, "port-ivy/Tide_Crush_Bluffs_0");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Waterfront_Park_4");
    }
}
