//Generated by rmud area generator
public class Tide_Crush_Bluffs_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Tide Crush Bluffs";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Tide_Crush_Bluffs_1");
      OpenLink(RMUD.Direction.SOUTHWEST, "port-ivy/Tide_Crush_Bluffs_2");
    }
}
