//Generated by rmud area generator
public class Waterfront_Park_3 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Waterfront_Park_4");
      OpenLink(RMUD.Direction.NORTHWEST, "port-ivy/Waterfront_Park_2");
    }
}
