//Generated by rmud area generator
public class Waterfront_Park_2 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

      OpenLink(RMUD.Direction.EAST, "port-ivy/Main_St_South_1");
      OpenLink(RMUD.Direction.SOUTHEAST, "port-ivy/Waterfront_Park_3");
      OpenLink(RMUD.Direction.WEST, "port-ivy/Waterfront_Park_1");
    }
}
