//Generated by rmud area generator
public class Waterfront_Park_0 : RMUD.Room {
    public override void Initialize() {
        Short = "Port Ivy - Waterfront Park";

      OpenLink(RMUD.Direction.NORTH, "port-ivy/Docks_2");
      OpenLink(RMUD.Direction.EAST, "port-ivy/Waterfront_Park_1");
    }
}
